<a href="https://colab.research.google.com/github/thefr33radical/codeblue/blob/master/fibo_binet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#### Fibonacci
#### T(C) = Brute Force Recursion O(n!), Matrix Optimization O(logn),Golden ratio O(1)
* https://www.mathsisfun.com/numbers/fibonacci-sequence.html
  

In [3]:


def fibo(n):
  """
  Function to Compute Fibo uing Recursive call
  """
  if n == 1 or n == 0:
    return 1
  return fibo(n-1)+fibo(n-2)
  
  
fibo(8-1)
  

21

In [10]:
import math
def fibo_binet(n):
  """
  Function to compute Fibonacci series using Binet's Formula
  """
  alpha = 1.618034

  fib_no = alpha**n - ( 1-alpha)**n
  fib_no = fib_no/math.sqrt(5)
  return int(fib_no)

fibo_binet(10)
  

55

In [37]:
import numpy as np
f = [[1,1],[1,0]]
f = np.array(f)


def fibo2(m,n):
  x = [[1,1],[1,0]]
  x = np.array(x)
  
  if n ==1:
    
    return x
  
  else:
    m = fibo2(m,n)
    z[0][0] = x[0][0]*m[0][0]+x[0][1]*m[1][0]
    z[0][1] = x[0][0]*m[0][0]+x[0][1]*m[1][0]
    z[1][0] = x[1][0]*m[0][0]+x[1][1]*m[1][0]
    z[1][1] = x[1][0]*m[0][1]+x[1][1]*m[1][1]
    return z

def fibo(m,n):
  x = [[1,1],[1,0]]
  x = np.array(x)
  
  if n ==1:
    
    return x
  m= np.matmul(x,fibo(m,n-1))
  print(m,n)
  return m

m2 = fibo(f,8)
print(m2)
#print(np.linalg.det(m2))
#print(np.matmul(np.square(f),np.square(f)))


[[2 1]
 [1 1]] 2
[[3 2]
 [2 1]] 3
[[5 3]
 [3 2]] 4
[[8 5]
 [5 3]] 5
[[13  8]
 [ 8  5]] 6
[[21 13]
 [13  8]] 7
[[34 21]
 [21 13]] 8
[[34 21]
 [21 13]]
